window.GAME_DATA = [
  {
    slug: "squeak-off",
    title: "Squeak Off!",
    category: "full",
    categoryLabel: "Full Game",
    genre: "3D Action Brawler",
    tagline: "Blast through waves of annoying squeaky toys and silence the chaos once and for all.",
    description: "Max, a retired veteran living in a shelter, has finally had enough of the endlessly squeaking toys. Fight through waves of mechanized toys, collect items, and take down their leader.",
    itch: "https://exity.itch.io/squeak-off",
    role: "Game Designer",
    platforms: "Windows · 1–2 players",
    engine: "Unity · Maya · Photoshop · Substance",
    release: "25 Aug 2025",
    status: "Released",
    download: "317–338 MB",
    videoId: "wCpRkn7GMN4",
    images: [
      "https://img.itch.zone/aW1hZ2UvMzg5MTAzNC8yMzcyNDY3Ni5wbmc%3D/347x500/fAxFPb.png",
      "https://img.itch.zone/aW1hZ2UvMzg5MTAzNC8yMzcyNDY4MC5wbmc%3D/347x500/%2BumCrh.png",
      "https://img.itch.zone/aW1hZ2UvMzg5MTAzNC8yMzcyNDY3OS5wbmc%3D/347x500/h2HQ9Y.png"
    ],
    controls: ["WASD — Move", "Left Mouse — Shoot", "E — Interact", "Space — Roll", "Q — Use item"],
    credits: [["Game Design", "Rishabh Jain"], ["Development", "Prince Choudhary"], ["Game Art", "Karthik Anil Kumar"]]
  },
  {
    slug: "entwined-reimagined",
    title: "ENTWINED: Reimagined",
    category: "full",
    categoryLabel: "Full Game",
    genre: "Narrative Puzzle Platformer",
    tagline: "Move between past and present, altering the environment through an invisible connection across time.",
    description: "Navigate between the present and the past using mysterious orbs to connect with a father trapped in child labour. Solve environmental challenges and uncover the story binding both timelines.",
    itch: "https://tkgluk.itch.io/entwined-reimagined",
    role: "Team Contributor",
    platforms: "Windows",
    engine: "Unity · Maya · Photoshop · Substance",
    release: "Released",
    status: "Released",
    download: "158 MB",
    images: [
      "https://img.itch.zone/aW1hZ2UvMzMzMDcwMC8xOTkwNTY1Ny5wbmc%3D/347x500/O3DDBD.png",
      "https://img.itch.zone/aW1hZ2UvMzMzMDcwMC8xOTkwNTY1Ni5wbmc%3D/347x500/u7jv3s.png",
      "https://img.itch.zone/aW1hZ2UvMzMzMDcwMC8xOTkwNTY1OC5wbmc%3D/347x500/%2F%2BMJBZ.png"
    ],
    controls: ["WASD — Move", "Space — Jump", "E — Switch worlds", "Left Mouse — Use pickaxe", "R — Restart"],
    credits: [["Team", "TkGluk · kartdoodle · Prince0p7 · Exity"]]
  },
  {
    slug: "nodesmith",
    title: "Nodesmith",
    category: "full",
    categoryLabel: "Full Game",
    genre: "Puzzle Platformer",
    tagline: "Evolve a machine-learning database of abilities through node-based real-time controls.",
    description: "Use a test subject to teach and evolve a database of abilities. Drag and connect nodes while the platforming test runs in real time, gradually expanding what the subject can do.",
    itch: "https://exity.itch.io/nodesmith",
    role: "Game Developer & Designer",
    platforms: "Windows",
    engine: "Unity · Photoshop · Audacity",
    release: "BYOG 2024 runner-up",
    status: "Released",
    download: "33 MB",
    videoId: "gZ14W4phJ0s",
    images: [
      "https://img.itch.zone/aW1hZ2UvMjk4ODkwMy8xNzg3OTczNi5wbmc%3D/347x500/1I4xKH.png",
      "https://img.itch.zone/aW1hZ2UvMjk4ODkwMy8xNzg3OTk5NC5wbmc%3D/347x500/%2B5Pgex.png",
      "https://img.itch.zone/aW1hZ2UvMjk4ODkwMy8xNzg3OTk5NS5wbmc%3D/347x500/aQ6yKL.png"
    ],
    controls: ["Read the dialogue prompts", "Drag and connect nodes", "Use the node graph to control the test subject"],
    credits: [["Game Development & Design", "Rishabh Jain · Prothom Pal"], ["Game Art", "Nandita Agrawal"]]
  },
  {
    slug: "statescape",
    title: "Statescape",
    category: "full",
    categoryLabel: "Full Game",
    genre: "Isometric Puzzle",
    tagline: "Escape a sci-fi laboratory using breathing and matter-state changing powers.",
    description: "Guide an intelligent alien ice cube through laboratory floors. Absorb limited air to change physical state, pass through compatible walls, and reach each evacuation tile before time runs out.",
    itch: "https://exity.itch.io/statescape",
    role: "Programming & Development",
    platforms: "Windows",
    engine: "Unity · Photoshop",
    release: "Released",
    status: "Released",
    download: "35 MB",
    images: [
      "https://img.itch.zone/aW1nLzE3NzI3NDU5LmpwZw%3D%3D/original/yIslI7.jpg",
      "https://img.itch.zone/aW1hZ2UvMjk2Mzc3MC8xNzcyNzUyMy5qcGc%3D/347x500/H0Et3k.jpg",
      "https://img.itch.zone/aW1hZ2UvMjk2Mzc3MC8xNzcyNzUyNC5wbmc%3D/347x500/0mhvZ1.png"
    ],
    controls: ["Left Mouse — Move to adjacent tiles", "Hold Right Mouse — Absorb air and change state", "R — Restart", "Esc — Menu"],
    credits: [["Programming & Development", "Rishabh Jain"], ["Tools & Systems", "Prince Choudhary"], ["Game Design & Sound", "Prothom Pal"], ["Game Art", "Karthik Anil Kumar"]]
  },
  {
    slug: "netherborne",
    title: "Netherborne",
    category: "full",
    categoryLabel: "Full Game",
    genre: "Couch Co-op Puzzle Platformer",
    tagline: "Two brothers must combine unique abilities to prove their innocence and escape the seven deadly sins.",
    description: "An atmospheric narrative-driven couch co-op platformer for two players. Work together, solve character-specific puzzle challenges, and progress through a stylised journey into the underworld.",
    itch: "https://exity.itch.io/netherborne",
    role: "Programming & Development",
    platforms: "Windows · Local co-op · 2 players",
    engine: "Unity · Photoshop",
    release: "3 Sep 2024",
    status: "Released",
    download: "76 MB",
    videoId: "RnvwLFvkwUE",
    images: [
      "https://img.itch.zone/aW1hZ2UvMjg2OTQ0Ni8xNzcxNzc4Ny5wbmc%3D/347x500/JJZsDs.png",
      "https://img.itch.zone/aW1hZ2UvMjg2OTQ0Ni8xNzcxNzc4Ni5wbmc%3D/347x500/qJJtkN.png",
      "https://img.itch.zone/aW1hZ2UvMjg2OTQ0Ni8xNzcxNzc4OS5wbmc%3D/347x500/%2FUqt1%2F.png"
    ],
    controls: ["Two input devices required", "Best played with one keyboard and one gamepad", "Press Enter on keyboard and Start on gamepad to spawn both characters"],
    credits: [["Programming & Development", "Rishabh Jain"], ["Game Art", "Karthik Anil Kumar"], ["Game Design", "Anubhav Roy"]]
  },
  {
    slug: "bean-em-all",
    title: "Bean 'Em All",
    category: "full",
    categoryLabel: "Full Game",
    genre: "Bullet Hell Action",
    tagline: "Start with no controls, earn abilities, and become the baddest bean in fast-paced bullet mayhem.",
    description: "A precision-focused action game built around gaining movement and combat abilities as you progress. Chain enemy defeats into a Bean-Reaction and grow from powerless bean to fully equipped fighter.",
    itch: "https://exity.itch.io/bean-em-all",
    role: "Game Designer",
    platforms: "Windows",
    engine: "Unity · Aseprite · Photoshop",
    release: "22 Jul 2024",
    status: "Released",
    download: "58 MB",
    videoId: "O94bNXereZU",
    images: [
      "https://img.itch.zone/aW1hZ2UvMjg0NzkwOC8xODc5Mzc0OC5qcGVn/347x500/YY%2B4gM.jpeg",
      "https://img.itch.zone/aW1hZ2UvMjg0NzkwOC8xODc5Mzc0OS5qcGVn/347x500/maiCap.jpeg",
      "https://img.itch.zone/aW1hZ2UvMjg0NzkwOC8xODc5Mzc0Ny5qcGVn/347x500/AzlbXY.jpeg"
    ],
    controls: ["WASD — Move", "Hold and release Left Mouse — Aim and shoot", "Space — Dash", "Attack adjacent enemies to trigger a Bean-Reaction"],
    credits: [["Game Design", "Rishabh Jain"], ["Game Development", "Prince Choudhary"], ["Game Art", "Karthik Anil Kumar"]]
  },
  {
    slug: "overryder",
    title: "OverRyder",
    category: "full",
    categoryLabel: "Full Game",
    genre: "Action",
    tagline: "Unleash mayhem across dystopian rooftops by overriding and controlling enemy bots.",
    description: "Steer across rooftops, jump between machines, override bots, and use their capabilities to continue climbing through the city.",
    itch: "https://exity.itch.io/overryder",
    role: "Game Designer",
    platforms: "Windows",
    engine: "Unity",
    release: "Released",
    status: "Released",
    download: "54 MB",
    images: [
      "https://img.itch.zone/aW1hZ2UvMjcyMTg5My8xNjIzMDE5My5qcGVn/347x500/79GKST.jpeg",
      "https://img.itch.zone/aW1hZ2UvMjcyMTg5My8xNjIzMDE5NC5qcGVn/347x500/l1NzCR.jpeg",
      "https://img.itch.zone/aW1hZ2UvMjcyMTg5My8xNjIzMDE5Mi5qcGVn/347x500/we3alf.jpeg"
    ],
    controls: ["A / D — Steer", "Right Mouse — Jump and override", "Left Mouse — Dash through objects"],
    credits: [["Game Design", "Rishabh Jain"], ["Development", "Prince Choudhary"], ["Game Art", "Karthik Anil Kumar · Shakib Khan"]]
  },
  {
    slug: "graycing",
    title: "Graycing",
    category: "full",
    categoryLabel: "Full Game",
    genre: "Arcade Racing",
    tagline: "Master toy cars, tracks, stunts, and championships in a black-and-white arcade racer.",
    description: "A compact arcade racing game with solo and split-screen play, multiple modes, seven tracks, nine cars, visual filters, and twelve championships.",
    itch: "https://exity.itch.io/graycing",
    role: "Developer",
    platforms: "Windows · Local multiplayer · 1–2 players",
    engine: "Unity · Blender · Photoshop · Audacity",
    release: "25 Apr 2021",
    status: "Released",
    download: "74 MB",
    images: [
      "https://img.itch.zone/aW1nLzU3NjI5NzUucG5n/original/HbC6J%2B.png",
      "https://img.itch.zone/aW1hZ2UvMTAxMTQ1OS81NzYyOTAzLnBuZw%3D%3D/347x500/h3%2FFdf.png",
      "https://img.itch.zone/aW1hZ2UvMTAxMTQ1OS81NzYyOTA0LnBuZw%3D%3D/347x500/7Q4IPN.png"
    ],
    controls: ["Keyboard controls are configurable", "Practice in Arcade and Time Trial", "Compete through twelve championships"],
    credits: [["Developer", "Rishabh Jain / Exity"]]
  },
  {
    slug: "statescape-jam",
    title: "Statescape Jam",
    category: "jam",
    categoryLabel: "Game Jam",
    genre: "Isometric Puzzle",
    tagline: "The original jam version of Statescape, built around breathing and state-changing powers.",
    description: "Move an intelligent alien ice cube through laboratory puzzles by consuming limited air and changing state to pass through different wall materials.",
    itch: "https://exity.itch.io/statescapejam",
    role: "Programming & Development",
    platforms: "Windows · Android",
    engine: "Unity · Aseprite · Photoshop · Audacity",
    release: "31 Jul 2023",
    status: "In development",
    download: "37 MB / 49 MB Android",
    images: [
      "https://img.itch.zone/aW1nLzEzMDAwMDI2LmpwZw%3D%3D/original/Icqda%2F.jpg",
      "https://img.itch.zone/aW1hZ2UvMjAzMzgxMS8xMzAwMDM5Ny5qcGc%3D/347x500/%2BUO2lV.jpg",
      "https://img.itch.zone/aW1hZ2UvMjAzMzgxMS8xMzk2MTk2Ny5wbmc%3D/347x500/BlOy%2F2.png"
    ],
    controls: ["Left Mouse — Move", "Hold Right Mouse — Change state", "R — Restart", "Esc — Menu"],
    credits: [["Programming & Development", "Rishabh Jain"], ["Tools & Systems", "Prince Choudhary"], ["Game Design & Sound", "Prothom Pal"], ["Game Art", "Karthik Anil Kumar · Abhishek Patil"]]
  },
  {
    slug: "something-fishy",
    title: "Something Fishy",
    category: "jam",
    categoryLabel: "Game Jam",
    genre: "Adventure / Tower Defence",
    tagline: "Control both the submarine and enemy fish to survive increasingly dangerous attack patterns.",
    description: "Prepare a defensive shield around the submarine, then enter the battle phase and manipulate attacking fish to keep the vessel alive until the timer expires.",
    itch: "https://exity.itch.io/something-fishy",
    role: "Programming & Game Design",
    platforms: "Windows",
    engine: "Game Jam Project",
    release: "GMTK Game Jam 2023",
    status: "Released",
    download: "35 MB",
    images: [
      "https://img.itch.zone/aW1nLzEyNzUyNzUwLmpwZWc%3D/original/5JSBsU.jpeg",
      "https://img.itch.zone/aW1hZ2UvMjE2MjU1Mi8xMjc1MjUzOS5wbmc%3D/347x500/9m7Wet.png",
      "https://img.itch.zone/aW1hZ2UvMjE2MjU1Mi8xMjc1MjUzNy5wbmc%3D/347x500/q4IgAN.png"
    ],
    controls: ["WASD — Move", "A / D — Rotate or steer", "Space — Begin battle", "R — Restart", "Esc — Menu"],
    credits: [["Programming & Game Design", "Rishabh Jain"], ["Lead Programming", "Prince Choudhary"], ["Game Art", "Sajal Shrivastava · Ayush Sharma"], ["Sound & Level Design", "Prothom Pal"]]
  },
  {
    slug: "paws-n-claws",
    title: "Paws n Claws",
    category: "jam",
    categoryLabel: "Game Jam",
    genre: "Puzzle Platformer",
    tagline: "A dog, a cat, and their goldfish friend plan a mischievous escape from home.",
    description: "Switch between a clever cat and a naive dog, use their different interactions, solve household puzzles, and remember to bring the goldfish along.",
    itch: "https://exity.itch.io/paws-n-claws",
    role: "Design & Development",
    platforms: "Windows",
    engine: "Game Jam Project",
    release: "QuestCraft 2024",
    status: "Released",
    download: "49 MB",
    images: [
      "https://img.itch.zone/aW1hZ2UvMjY3MTM0MC8xNTkyMjM1NC5wbmc%3D/347x500/mIohLK.png",
      "https://img.itch.zone/aW1hZ2UvMjY3MTM0MC8xNTkyMjM1My5wbmc%3D/347x500/3%2FTOyA.png",
      "https://img.itch.zone/aW1hZ2UvMjY3MTM0MC8xNTkyMjM1NS5wbmc%3D/347x500/0cP%2FRb.png"
    ],
    controls: ["A / D — Move", "Space — Jump", "Q — Switch characters", "E — Interact", "W — Pick up / push", "S — Drop"],
    credits: [["Design & Development", "Rishabh Jain"], ["Programming", "Prince Choudhary"], ["Game Art", "Karthik Anil Kumar"]]
  },
  {
    slug: "gun-it",
    title: "Gun-It",
    category: "jam",
    categoryLabel: "Game Jam",
    genre: "Math Platformer",
    tagline: "Shoot through operators and numbers to land on the correct value of X.",
    description: "A two-day game-jam experiment where recoil is movement and arithmetic is level design. Aim the gun, project yourself through the equation, and land on the correct answer.",
    itch: "https://exity.itch.io/gun-it",
    role: "Game Designer",
    platforms: "Windows",
    engine: "Unity · Photoshop",
    release: "Built in 2 days",
    status: "Released",
    download: "41 MB",
    images: [
      "https://img.itch.zone/aW1hZ2UvMjU2NzIzNS8xNTI3ODY1OC5qcGc%3D/347x500/c7bjYz.jpg",
      "https://img.itch.zone/aW1hZ2UvMjU2NzIzNS8xNTI3ODY1OS5qcGc%3D/347x500/%2F%2FoD54.jpg"
    ],
    controls: ["Mouse — Rotate gun", "Drag farther — Increase visible range", "Left Mouse — Shoot", "R — Restart", "Esc — Menu"],
    credits: [["Game Design", "Rishabh Jain"], ["Programming", "Prince Choudhary"], ["Game Art", "Garv Sethi"]]
  },
  {
    slug: "nezumi",
    title: "Nezumi",
    category: "jam",
    categoryLabel: "Game Jam",
    genre: "Adventure",
    tagline: "Move through shadows from sewer to sewer in a monochrome pixel-art adventure.",
    description: "A five-level game made from scratch in two days. Navigate a carefully animated monochrome world, trust the timing, and stay safe in the dark.",
    itch: "https://prince0p7.itch.io/nezumi",
    role: "Team Member",
    platforms: "Windows",
    engine: "Game Jam Project",
    release: "Built in 2 days",
    status: "Released",
    download: "71 MB",
    images: [
      "https://img.itch.zone/aW1nLzE0MzkwMzU1LmpwZw%3D%3D/original/XWFPim.jpg",
      "https://img.itch.zone/aW1hZ2UvMjQyOTc1MC8xNDM5MDE2NS5qcGc%3D/347x500/fnJFbY.jpg",
      "https://img.itch.zone/aW1hZ2UvMjQyOTc1MC8xNDM4NTIzMy5wbmc%3D/347x500/S1zA2v.png"
    ],
    controls: ["WASD — Move", "Space — Interact"],
    credits: [["Team arKince", "Karthik Anilkumar · Prince Choudhary · Rishabh Jain"]]
  },
  {
    slug: "fortune-smiles-upon-you",
    title: "Fortune Smiles Upon You",
    category: "jam",
    categoryLabel: "Game Jam",
    genre: "Point-and-Click Puzzle",
    tagline: "Foretell a client's fate, then manipulate the scene to make the fortune come true in your favour.",
    description: "Explore each scene, interact with objects, and find the sequence that fulfils the fortune you have just predicted. Built from scratch in two days with four levels.",
    itch: "https://prince0p7.itch.io/fortune-smiles-upon-you",
    role: "Game Designer",
    platforms: "Windows",
    engine: "Game Jam Project",
    release: "Built in 2 days",
    status: "Released",
    download: "33 MB",
    images: [
      "https://img.itch.zone/aW1nLzE1Mzk4MTI5LnBuZw%3D%3D/original/%2Bm%2F%2F%2Fu.png",
      "https://img.itch.zone/aW1hZ2UvMjU4NTcxNi8xNTM5ODExMi5wbmc%3D/347x500/CA0S7f.png",
      "https://img.itch.zone/aW1hZ2UvMjU4NTcxNi8xNTM5ODExMy5wbmc%3D/347x500/p2hHAY.png"
    ],
    controls: ["Click — Interact", "Click and hold — Move objects"],
    credits: [["Game Design", "Rishabh Jain"], ["Programming", "Prince Choudhary"], ["Game Art", "Karthik Anilkumar"]]
  },
  {
    slug: "entwined",
    title: "Entwined",
    category: "jam",
    categoryLabel: "Game Jam",
    genre: "Puzzle Platformer",
    tagline: "Control one character, then watch the other rewind and replay the same movement path.",
    description: "Plan movement for the main character while a reflected character follows the recorded inputs in another world. Use the projected trail to coordinate both paths and solve puzzles.",
    itch: "https://exity.itch.io/entwined",
    role: "Programmer / Designer",
    platforms: "Windows",
    engine: "Game Jam Project",
    release: "BYOG 2023",
    status: "Released",
    download: "40 MB",
    images: [
      "https://img.itch.zone/aW1hZ2UvMjI2NzAwNS8xMzQzNjA4Ni5wbmc%3D/347x500/j5q3tB.png",
      "https://img.itch.zone/aW1hZ2UvMjI2NzAwNS8xMzg4NTU4MS5wbmc%3D/347x500/nWyRB6.png",
      "https://img.itch.zone/aW1hZ2UvMjI2NzAwNS8xMzg4NTU5NS5wbmc%3D/347x500/elKWtr.png"
    ],
    controls: ["A / D — Move", "Space — Jump", "Jump while airborne — Dash forward"],
    credits: [["Programming / Design", "Rishabh Jain"], ["Lead Programming", "Prince Choudhary"], ["Game Design / Sound", "Prothom Pal"], ["Game Art", "Garv Sethi · Akshat Mandal"]]
  },
  {
    slug: "divine-darkness",
    title: "Divine Darkness",
    category: "jam",
    categoryLabel: "Game Jam",
    genre: "Top-Down Puzzle",
    tagline: "Fuse the player with their shadow to solve compact movement puzzles.",
    description: "Coordinate the divine and dark sides of the player, use teleportation, and avoid remaining on the same tile for too long.",
    itch: "https://exity.itch.io/divine-darkness",
    role: "Development & Programming",
    platforms: "HTML5 · Windows",
    engine: "Unity · Inkscape · Audacity",
    release: "Brackeys Game Jam 2022.2",
    status: "In development",
    download: "22–24 MB",
    images: [
      "https://img.itch.zone/aW1hZ2UvMTY4MTMzNi85OTAxMTU1LnBuZw%3D%3D/347x500/Fo%2BNm4.png",
      "https://img.itch.zone/aW1hZ2UvMTY4MTMzNi85OTAxMTU2LnBuZw%3D%3D/347x500/SBRKbP.png",
      "https://img.itch.zone/aW1hZ2UvMTY4MTMzNi85OTAxMTY1LnBuZw%3D%3D/347x500/C7AMXb.png"
    ],
    controls: ["WASD — Move", "E — Teleport", "Staying on the same tile for three moves causes game over"],
    credits: [["Development & Programming", "Rishabh Jain"], ["Art · Design · Music", "Prothom Pal"]]
  },
  {
    slug: "project-xmas",
    title: "Project Xmas",
    category: "prototype",
    categoryLabel: "Prototype",
    genre: "First-Person Horror",
    tagline: "Restore power before Christmas while something stalks the dark forest.",
    description: "A Christmas-themed first-person horror game made in seven days. Search the forest for the electrical-room key, return power to the village, and avoid the creature roaming outside.",
    itch: "https://exity.itch.io/project-xmas",
    role: "Developer",
    platforms: "Windows · macOS · Linux",
    engine: "Unity · Blender",
    release: "21 Dec 2021",
    status: "Released",
    download: "49–52 MB",
    images: [
      "https://img.itch.zone/aW1hZ2UvMTMzMDE4Mi83NzM2MDk5LnBuZw%3D%3D/347x500/q65cz3.png",
      "https://img.itch.zone/aW1hZ2UvMTMzMDE4Mi83NzM2MTAwLnBuZw%3D%3D/347x500/574g86.png",
      "https://img.itch.zone/aW1hZ2UvMTMzMDE4Mi83NzM2MTAxLnBuZw%3D%3D/347x500/vPj23D.png"
    ],
    controls: ["WASD — Move", "E — Interact", "Esc — Pause / Back"],
    credits: [["Development", "Rishabh Jain / Exity"]]
  }
];
