window.GAME_DATA = [
  {
    slug: "squeak-off",
    title: "Squeak Off!",
    cover: "../assets/games/squeak-off/shot-1.png",
    category: "full",
    categoryLabel: "Full Game",
    genre: "3D Action Brawler",
    tagline: "Blast through waves of annoying squeaky toys and silence the chaos once and for all.",
    description: "Max, a retired veteran living in a shelter, has finally had enough of the endlessly squeaking toys. Fight through waves of mechanized toys, collect items, and take down their leader.",
    itch: "https://exity.itch.io/squeak-off",
    role: "Game Designer",
    platforms: "Windows · 1–2 players",
    engine: "Unity · Maya · Photoshop · Substance",
    release: "25 Aug 2025",
    status: "Released",
    download: "317–338 MB",
    videoId: "wCpRkn7GMN4",
    controls: ["WASD — Move", "Left Mouse — Shoot", "E — Interact", "Space — Roll", "Q — Use item"],
    credits: [["Game Design", "Rishabh Jain"], ["Development", "Prince Choudhary"], ["Game Art", "Karthik Anil Kumar"]]
  },
  {
    slug: "entwined-reimagined",
    title: "ENTWINED: Reimagined",
    cover: "../assets/games/entwined-reimagined/cover.svg",
    category: "full",
    categoryLabel: "Full Game",
    genre: "Narrative Puzzle Platformer",
    tagline: "Move between past and present, altering the environment through an invisible connection across time.",
    description: "Navigate between the present and the past using mysterious orbs to connect with a father trapped in child labour. Solve environmental challenges and uncover the story binding both timelines.",
    itch: "https://tkgluk.itch.io/entwined-reimagined",
    role: "Team Contributor",
    platforms: "Windows",
    engine: "Unity · Maya · Photoshop · Substance",
    release: "Released",
    status: "Released",
    download: "158 MB",
    controls: ["WASD — Move", "Space — Jump", "E — Switch worlds", "Left Mouse — Use pickaxe", "R — Restart"],
    credits: [["Team", "TkGluk · kartdoodle · Prince0p7 · Exity"]]
  },
  {
    slug: "nodesmith",
    title: "Nodesmith",
    cover: "../assets/games/nodesmith/shot-1.png",
    category: "full",
    categoryLabel: "Full Game",
    genre: "Puzzle Platformer",
    tagline: "Evolve a machine-learning database of abilities through node-based real-time controls.",
    description: "Use a test subject to teach and evolve a database of abilities. Drag and connect nodes while the platforming test runs in real time, gradually expanding what the subject can do.",
    itch: "https://exity.itch.io/nodesmith",
    role: "Game Developer & Designer",
    platforms: "Windows",
    engine: "Unity · Photoshop · Audacity",
    release: "BYOG 2024 runner-up",
    status: "Released",
    download: "33 MB",
    videoId: "gZ14W4phJ0s",
    controls: ["Read the dialogue prompts", "Drag and connect nodes", "Use the node graph to control the test subject"],
    credits: [["Game Development & Design", "Rishabh Jain · Prothom Pal"], ["Game Art", "Nandita Agrawal"]]
  },
  {
    slug: "statescape",
    title: "Statescape",
    cover: "../assets/games/statescape/cover.svg",
    category: "full",
    categoryLabel: "Full Game",
    genre: "Isometric Puzzle",
    tagline: "Escape a sci-fi laboratory using breathing and matter-state changing powers.",
    description: "Guide an intelligent alien ice cube through laboratory floors. Absorb limited air to change physical state, pass through compatible walls, and reach each evacuation tile before time runs out.",
    itch: "https://exity.itch.io/statescape",
    role: "Programming & Development",
    platforms: "Windows",
    engine: "Unity · Photoshop",
    release: "Released",
    status: "Released",
    download: "35 MB",
    controls: ["Left Mouse — Move to adjacent tiles", "Hold Right Mouse — Absorb air and change state", "R — Restart", "Esc — Menu"],
    credits: [["Programming & Development", "Rishabh Jain"], ["Tools & Systems", "Prince Choudhary"], ["Game Design & Sound", "Prothom Pal"], ["Game Art", "Karthik Anil Kumar"]]
  },
  {
    slug: "netherborne",
    title: "Netherborne",
    cover: "../assets/games/netherborne/shot-1.png",
    category: "full",
    categoryLabel: "Full Game",
    genre: "Couch Co-op Puzzle Platformer",
    tagline: "Two brothers must combine unique abilities to prove their innocence and escape the seven deadly sins.",
    description: "An atmospheric narrative-driven couch co-op platformer for two players. Work together, solve character-specific puzzle challenges, and progress through a stylised journey into the underworld.",
    itch: "https://exity.itch.io/netherborne",
    role: "Programming & Development",
    platforms: "Windows · Local co-op · 2 players",
    engine: "Unity · Photoshop",
    release: "3 Sep 2024",
    status: "Released",
    download: "76 MB",
    videoId: "RnvwLFvkwUE",
    controls: ["Two input devices required", "Best played with one keyboard and one gamepad", "Press Enter on keyboard and Start on gamepad to spawn both characters"],
    credits: [["Programming & Development", "Rishabh Jain"], ["Game Art", "Karthik Anil Kumar"], ["Game Design", "Anubhav Roy"]]
  },
  {
    slug: "bean-em-all",
    title: "Bean 'Em All",
    cover: "../assets/games/bean-em-all/shot-1.jpeg",
    category: "full",
    categoryLabel: "Full Game",
    genre: "Bullet Hell Action",
    tagline: "Start with no controls, earn abilities, and become the baddest bean in fast-paced bullet mayhem.",
    description: "A precision-focused action game built around gaining movement and combat abilities as you progress. Chain enemy defeats into a Bean-Reaction and grow from powerless bean to fully equipped fighter.",
    itch: "https://exity.itch.io/bean-em-all",
    role: "Game Designer",
    platforms: "Windows",
    engine: "Unity · Aseprite · Photoshop",
    release: "22 Jul 2024",
    status: "Released",
    download: "58 MB",
    videoId: "O94bNXereZU",
    controls: ["WASD — Move", "Hold and release Left Mouse — Aim and shoot", "Space — Dash", "Attack adjacent enemies to trigger a Bean-Reaction"],
    credits: [["Game Design", "Rishabh Jain"], ["Game Development", "Prince Choudhary"], ["Game Art", "Karthik Anil Kumar"]]
  },
  {
    slug: "overryder",
    title: "OverRyder",
    cover: "../assets/games/overryder/cover.svg",
    category: "full",
    categoryLabel: "Full Game",
    genre: "Action",
    tagline: "Unleash mayhem across dystopian rooftops by overriding and controlling enemy bots.",
    description: "Steer across rooftops, jump between machines, override bots, and use their capabilities to continue climbing through the city.",
    itch: "https://exity.itch.io/overryder",
    role: "Game Designer",
    platforms: "Windows",
    engine: "Unity",
    release: "Released",
    status: "Released",
    download: "54 MB",
    controls: ["A / D — Steer", "Right Mouse — Jump and override", "Left Mouse — Dash through objects"],
    credits: [["Game Design", "Rishabh Jain"], ["Development", "Prince Choudhary"], ["Game Art", "Karthik Anil Kumar · Shakib Khan"]]
  },
  {
    slug: "graycing",
    title: "Graycing",
    cover: "../assets/games/graycing/shot-1.png",
    category: "full",
    categoryLabel: "Full Game",
    genre: "Arcade Racing",
    tagline: "Master toy cars, tracks, stunts, and championships in a black-and-white arcade racer.",
    description: "A compact arcade racing game with solo and split-screen play, multiple modes, seven tracks, nine cars, visual filters, and twelve championships.",
    itch: "https://exity.itch.io/graycing",
    role: "Developer",
    platforms: "Windows · Local multiplayer · 1–2 players",
    engine: "Unity · Blender · Photoshop · Audacity",
    release: "25 Apr 2021",
    status: "Released",
    download: "74 MB",
    controls: ["Keyboard controls are configurable", "Practice in Arcade and Time Trial", "Compete through twelve championships"],
    credits: [["Developer", "Rishabh Jain / Exity"]]
  },
  {
    slug: "something-fishy",
    title: "Something Fishy",
    cover: "../assets/games/something-fishy/cover.svg",
    category: "jam",
    categoryLabel: "Game Jam",
    genre: "Adventure / Tower Defence",
    tagline: "Control both the submarine and enemy fish to survive increasingly dangerous attack patterns.",
    description: "Prepare a defensive shield around the submarine, then enter the battle phase and manipulate attacking fish to keep the vessel alive until the timer expires.",
    itch: "https://exity.itch.io/something-fishy",
    role: "Programming & Game Design",
    platforms: "Windows",
    engine: "Game Jam Project",
    release: "GMTK Game Jam 2023",
    status: "Released",
    download: "35 MB",
    controls: ["WASD — Move", "A / D — Rotate or steer", "Space — Begin battle", "R — Restart", "Esc — Menu"],
    credits: [["Programming & Game Design", "Rishabh Jain"], ["Lead Programming", "Prince Choudhary"], ["Game Art", "Sajal Shrivastava · Ayush Sharma"], ["Sound & Level Design", "Prothom Pal"]]
  },
  {
    slug: "paws-n-claws",
    title: "Paws n Claws",
    cover: "../assets/games/paws-n-claws/cover.svg",
    category: "jam",
    categoryLabel: "Game Jam",
    genre: "Puzzle Platformer",
    tagline: "A dog, a cat, and their goldfish friend plan a mischievous escape from home.",
    description: "Switch between a clever cat and a naive dog, use their different interactions, solve household puzzles, and remember to bring the goldfish along.",
    itch: "https://exity.itch.io/paws-n-claws",
    role: "Design & Development",
    platforms: "Windows",
    engine: "Game Jam Project",
    release: "QuestCraft 2024",
    status: "Released",
    download: "49 MB",
    controls: ["A / D — Move", "Space — Jump", "Q — Switch characters", "E — Interact", "W — Pick up / push", "S — Drop"],
    credits: [["Design & Development", "Rishabh Jain"], ["Programming", "Prince Choudhary"], ["Game Art", "Karthik Anil Kumar"]]
  },
  {
    slug: "gun-it",
    title: "Gun-It",
    cover: "../assets/games/gun-it/cover.svg",
    category: "jam",
    categoryLabel: "Game Jam",
    genre: "Math Platformer",
    tagline: "Shoot through operators and numbers to land on the correct value of X.",
    description: "A two-day game-jam experiment where recoil is movement and arithmetic is level design. Aim the gun, project yourself through the equation, and land on the correct answer.",
    itch: "https://exity.itch.io/gun-it",
    role: "Game Designer",
    platforms: "Windows",
    engine: "Unity · Photoshop",
    release: "Built in 2 days",
    status: "Released",
    download: "41 MB",
    controls: ["Mouse — Rotate gun", "Drag farther — Increase visible range", "Left Mouse — Shoot", "R — Restart", "Esc — Menu"],
    credits: [["Game Design", "Rishabh Jain"], ["Programming", "Prince Choudhary"], ["Game Art", "Garv Sethi"]]
  },
  {
    slug: "nezumi",
    title: "Nezumi",
    cover: "../assets/games/nezumi/cover.svg",
    category: "jam",
    categoryLabel: "Game Jam",
    genre: "Adventure",
    tagline: "Move through shadows from sewer to sewer in a monochrome pixel-art adventure.",
    description: "A five-level game made from scratch in two days. Navigate a carefully animated monochrome world, trust the timing, and stay safe in the dark.",
    itch: "https://prince0p7.itch.io/nezumi",
    role: "Team Member",
    platforms: "Windows",
    engine: "Game Jam Project",
    release: "Built in 2 days",
    status: "Released",
    download: "71 MB",
    controls: ["WASD — Move", "Space — Interact"],
    credits: [["Team arKince", "Karthik Anilkumar · Prince Choudhary · Rishabh Jain"]]
  },
  {
    slug: "fortune-smiles-upon-you",
    title: "Fortune Smiles Upon You",
    cover: "../assets/games/fortune-smiles-upon-you/cover.svg",
    category: "jam",
    categoryLabel: "Game Jam",
    genre: "Point-and-Click Puzzle",
    tagline: "Foretell a client's fate, then manipulate the scene to make the fortune come true in your favour.",
    description: "Explore each scene, interact with objects, and find the sequence that fulfils the fortune you have just predicted. Built from scratch in two days with four levels.",
    itch: "https://prince0p7.itch.io/fortune-smiles-upon-you",
    role: "Game Designer",
    platforms: "Windows",
    engine: "Game Jam Project",
    release: "Built in 2 days",
    status: "Released",
    download: "33 MB",
    controls: ["Click — Interact", "Click and hold — Move objects"],
    credits: [["Game Design", "Rishabh Jain"], ["Programming", "Prince Choudhary"], ["Game Art", "Karthik Anilkumar"]]
  },
  {
    slug: "entwined",
    title: "Entwined",
    cover: "../assets/games/entwined/cover.svg",
    category: "jam",
    categoryLabel: "Game Jam",
    genre: "Puzzle Platformer",
    tagline: "Control one character, then watch the other rewind and replay the same movement path.",
    description: "Plan movement for the main character while a reflected character follows the recorded inputs in another world. Use the projected trail to coordinate both paths and solve puzzles.",
    itch: "https://exity.itch.io/entwined",
    role: "Programmer / Designer",
    platforms: "Windows",
    engine: "Game Jam Project",
    release: "BYOG 2023",
    status: "Released",
    download: "40 MB",
    controls: ["A / D — Move", "Space — Jump", "Jump while airborne — Dash forward"],
    credits: [["Programming / Design", "Rishabh Jain"], ["Lead Programming", "Prince Choudhary"], ["Game Design / Sound", "Prothom Pal"], ["Game Art", "Garv Sethi · Akshat Mandal"]]
  },
  {
    slug: "divine-darkness",
    title: "Divine Darkness",
    cover: "../assets/games/divine-darkness/cover.svg",
    category: "jam",
    categoryLabel: "Game Jam",
    genre: "Top-Down Puzzle",
    tagline: "Fuse the player with their shadow to solve compact movement puzzles.",
    description: "Coordinate the divine and dark sides of the player, use teleportation, and avoid remaining on the same tile for too long.",
    itch: "https://exity.itch.io/divine-darkness",
    role: "Development & Programming",
    platforms: "HTML5 · Windows",
    engine: "Unity · Inkscape · Audacity",
    release: "Brackeys Game Jam 2022.2",
    status: "In development",
    download: "22–24 MB",
    controls: ["WASD — Move", "E — Teleport", "Staying on the same tile for three moves causes game over"],
    credits: [["Development & Programming", "Rishabh Jain"], ["Art · Design · Music", "Prothom Pal"]]
  },
  {
    slug: "project-xmas",
    title: "Project Xmas",
    cover: "../assets/games/project-xmas/cover.svg",
    category: "prototype",
    categoryLabel: "Prototype",
    genre: "First-Person Horror",
    tagline: "Restore power before Christmas while something stalks the dark forest.",
    description: "A Christmas-themed first-person horror game made in seven days. Search the forest for the electrical-room key, return power to the village, and avoid the creature roaming outside.",
    itch: "https://exity.itch.io/project-xmas",
    role: "Developer",
    platforms: "Windows · macOS · Linux",
    engine: "Unity · Blender",
    release: "21 Dec 2021",
    status: "Released",
    download: "49–52 MB",
    controls: ["WASD — Move", "E — Interact", "Esc — Pause / Back"],
    credits: [["Development", "Rishabh Jain / Exity"]]
  }
];
